package com.seatly.backend.auth.type;

public interface AuthMessageKeys {

    String EMAIL_ALREADY_REGISTERED = "AUTH_ERROR_EMAIL_ALREADY_REGISTERED";
    String INVALID_CREDENTIALS = "AUTH_ERROR_INVALID_CREDENTIALS";
    String PASSWORD_TOO_LONG = "AUTH_ERROR_PASSWORD_TOO_LONG";

    String NAME_REQUIRED = "AUTH_ERROR_NAME_REQUIRED";
    String NAME_TOO_LONG = "AUTH_ERROR_NAME_TOO_LONG";
    String EMAIL_REQUIRED = "AUTH_ERROR_EMAIL_REQUIRED";
    String EMAIL_INVALID = "AUTH_ERROR_EMAIL_INVALID";
    String EMAIL_TOO_LONG = "AUTH_ERROR_EMAIL_TOO_LONG";
    String PASSWORD_REQUIRED = "AUTH_ERROR_PASSWORD_REQUIRED";
    String PASSWORD_TOO_SHORT = "AUTH_ERROR_PASSWORD_TOO_SHORT";
    String BIO_TOO_LONG = "AUTH_ERROR_BIO_TOO_LONG";
}
