package com.seatly.backend.common.type;

public interface CommonMessageKeys {

    String AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED";
    String ACCESS_DENIED = "ACCESS_DENIED";
    String DATA_INTEGRITY_VIOLATION = "DATA_INTEGRITY_VIOLATION";
    String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    String MALFORMED_REQUEST_BODY = "MALFORMED_REQUEST_BODY";
    String INVALID_PARAMETER = "INVALID_PARAMETER";
    String PAGE_NUMBER_INVALID = "PAGE_NUMBER_INVALID";
    String PAGE_SIZE_INVALID = "PAGE_SIZE_INVALID";
}
